import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export async function exportToPDF(claims, summary, aiScore, inputText) {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;
  
  // Header
  doc.setFillColor(99, 102, 241);
  doc.rect(0, 0, pageWidth, 18, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('FactGuard — Accuracy Report', 14, 12);
  doc.setFontSize(9);
  doc.text(new Date().toLocaleString(), pageWidth - 14, 12, { align: 'right' });
  
  y = 30;
  
  // Summary metrics
  doc.setTextColor(26, 26, 46);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('SUMMARY', 14, y);
  y += 6;
  
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 120);
  doc.text(`Accuracy Score: ${summary.accuracy_score}%  |  ` +
           `True: ${summary.true}  |  False: ${summary.false}  |  ` +
           `Unverifiable: ${summary.unverifiable}  |  ` +
           `Credibility: ${summary.credibility}`, 14, y);
  y += 4;
  
  doc.text(`AI-Generated Content Probability: ${Math.round((aiScore || 0) * 100)}%`, 14, y);
  y += 10;
  
  // Divider
  doc.setDrawColor(230, 230, 250);
  doc.line(14, y, pageWidth - 14, y);
  y += 8;
  
  // Claims
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(26, 26, 46);
  doc.text('DETAILED CLAIM ANALYSIS', 14, y);
  y += 8;
  
  const verdictColors = {
    'TRUE': [16, 185, 129],
    'FALSE': [239, 68, 68],
    'PARTIALLY TRUE': [245, 158, 11],
    'UNVERIFIABLE': [148, 163, 184]
  };
  
  for (const claim of claims) {
    if (y > 260) { doc.addPage(); y = 20; }
    
    // Claim number
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(148, 163, 184);
    doc.text(`CLAIM #${claim.id}`, 14, y);
    
    // Verdict pill
    const color = verdictColors[claim.verdict] || [148, 163, 184];
    doc.setFillColor(...color);
    const pillX = pageWidth - 40;
    doc.roundedRect(pillX, y - 5, 26, 7, 3, 3, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(6);
    doc.text(claim.verdict || "UNKNOWN", pillX + 13, y, { align: 'center' });
    y += 6;
    
    // Claim text
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(26, 26, 46);
    const lines = doc.splitTextToSize(claim.claim || "", pageWidth - 28);
    doc.text(lines, 14, y);
    y += lines.length * 5 + 2;
    
    // Confidence
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(`Confidence: ${Math.round((claim.confidence || 0) * 100)}%`, 14, y);
    y += 4;
    
    // Sources
    if (claim.sources && claim.sources.length > 0) {
      doc.setFontSize(7);
      doc.setTextColor(99, 102, 241);
      const sourceText = claim.sources.slice(0,2).map(s => s.url).join('  |  ');
      const sourceLines = doc.splitTextToSize(sourceText, pageWidth - 28);
      doc.text(sourceLines, 14, y);
      y += sourceLines.length * 4;
    }
    
    y += 6;
    doc.setDrawColor(240, 240, 255);
    doc.line(14, y, pageWidth - 14, y);
    y += 6;
  }
  
  // Footer
  doc.setFontSize(8);
  doc.setTextColor(180, 180, 200);
  doc.text('Generated by FactGuard AI · factguard.app', 
           pageWidth / 2, 290, { align: 'center' });
  
  doc.save(`factguard-report-${Date.now()}.pdf`);
}
